### ISSUE TITLE
Dangling group headline when using --exclude-start flag

### ISSUE THREAD

**Issue by marcelkottmann** [mabels/sip-changelog#11]
The new --exclude-start flag doesn't exclude tags that are on the start commit-hash and that can be matched with the --group-by-tag regex parameter:

e.g.:
`npx sip-changelog --start rb-LUX-start --exclude-start --group-by-tag=rb-LUX-start `

The output ends with a dangling group headline.

**Comment by mabels** [comment]
is fixed in 1.0.2
